# Downloads and self-hosts the THE RECORD font stack into assets/fonts/ (latin subset only, woff2).
# Re-run any time (it overwrites). If offline, the site falls back to system stacks and still ships.
# Usage:  powershell -ExecutionPolicy Bypass -File scripts\fetch-fonts.ps1
$ErrorActionPreference = 'Stop'
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
$root = Split-Path -Parent $PSScriptRoot
$out  = Join-Path $root 'assets\fonts'
New-Item -ItemType Directory -Force -Path $out | Out-Null

$ua  = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36'
# Fraunces is variable (roman + italic, each one file covering opsz 9..144 and the weight range;
# SOFT/WONK stay at their restrained 0 default, so we don't request them). IBM Plex Mono is a
# static cut. fonts.css is regenerated below with proper font-weight RANGES for the variable faces.
# Axis order for the css2 API must be alphabetical: registered lowercase (ital,opsz,wght) first.
$api = 'https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,300..900;1,9..144,300..900&family=IBM+Plex+Mono:wght@500&display=swap'

try {
  $css = (Invoke-WebRequest -Uri $api -UserAgent $ua -UseBasicParsing).Content
} catch {
  Write-Host "Could not reach Google Fonts: $($_.Exception.Message)"
  Write-Host "That's OK - the site uses system fallbacks until you re-run this online."
  return
}

$slug  = @{ 'Fraunces' = 'fraunces'; 'IBM Plex Mono' = 'ibm-plex-mono' }
$rx    = [regex]"/\*\s*(?<sub>[\w-]+)\s*\*/\s*@font-face\s*\{(?<body>[^}]*)\}"
$faces = @()
foreach ($m in $rx.Matches($css)) {
  if ($m.Groups['sub'].Value -ne 'latin') { continue }   # latin subset covers our English text + punctuation
  $b   = $m.Groups['body'].Value
  $fam = ([regex]"font-family:\s*'([^']+)'").Match($b).Groups[1].Value
  $sty = ([regex]"font-style:\s*(\w+)").Match($b).Groups[1].Value
  $wgt = ([regex]"font-weight:\s*([\d ]+\d)").Match($b).Groups[1].Value      # "500" or "200 800"
  $str = ([regex]"font-stretch:\s*([^;]+);").Match($b).Groups[1].Value      # "" or "75% 100%"
  $url = ([regex]"src:\s*url\(([^)]+)\)").Match($b).Groups[1].Value
  $ur  = ([regex]"unicode-range:\s*([^;]+);").Match($b).Groups[1].Value
  $name = $slug[$fam]
  if (-not $name) { continue }
  if ($sty -eq 'italic') { $name += '-italic' }
  if ($wgt -match ' ') { $name += '-var.woff2' } else { $name += "-$wgt.woff2" }
  Invoke-WebRequest -Uri $url -UserAgent $ua -UseBasicParsing -OutFile (Join-Path $out $name)
  $faces += [pscustomobject]@{ fam = $fam; sty = $sty; wgt = $wgt; str = $str.Trim(); file = $name; ur = $ur }
  Write-Host "  downloaded $name ($($fam) $($wgt))"
}

if ($faces.Count -eq 0) { Write-Host "No latin faces parsed - leaving fallbacks in place."; return }

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("/* Self-hosted fonts for THE RECORD. Generated by scripts/fetch-fonts.ps1 - do not hand-edit. */")
foreach ($f in $faces) {
  [void]$sb.AppendLine("@font-face {")
  [void]$sb.AppendLine("  font-family: '$($f.fam)';")
  [void]$sb.AppendLine("  font-style: $($f.sty);")
  [void]$sb.AppendLine("  font-weight: $($f.wgt);")
  if ($f.str) { [void]$sb.AppendLine("  font-stretch: $($f.str);") }
  [void]$sb.AppendLine("  font-display: swap;")
  [void]$sb.AppendLine("  src: url('./$($f.file)') format('woff2');")
  if ($f.ur) { [void]$sb.AppendLine("  unicode-range: $($f.ur);") }
  [void]$sb.AppendLine("}")
}
[System.IO.File]::WriteAllText((Join-Path $out 'fonts.css'), $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Wrote assets/fonts/fonts.css with $($faces.Count) faces."
