# Downloads and self-hosts the two font families into assets/fonts/ (latin subset only, woff2).
# Re-run any time (it overwrites). If offline, the site falls back to system serif/mono stacks and still ships.
# Usage:  powershell -ExecutionPolicy Bypass -File scripts\fetch-fonts.ps1
$ErrorActionPreference = 'Stop'
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
$root = Split-Path -Parent $PSScriptRoot
$out  = Join-Path $root 'assets\fonts'
New-Item -ItemType Directory -Force -Path $out | Out-Null

$ua  = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36'
# Newsreader is variable (one roman file covers the weight axis, plus one italic); Inter is variable;
# IBM Plex Mono is a static cut. NOTE: assets/fonts/fonts.css is hand-maintained (variable faces are
# deduped to one file with a font-weight RANGE) — re-running this is for refreshing the woff2 bytes.
$api = 'https://fonts.googleapis.com/css2?family=Newsreader:ital,opsz,wght@0,6..72,400;0,6..72,600;1,6..72,400&family=Inter:wght@400;500;600&family=IBM+Plex+Mono:wght@500&display=swap'

try {
  $css = (Invoke-WebRequest -Uri $api -UserAgent $ua -UseBasicParsing).Content
} catch {
  Write-Host "Could not reach Google Fonts: $($_.Exception.Message)"
  Write-Host "That's OK - the site uses system fallbacks (Georgia / Consolas) until you re-run this online."
  return
}

$slug  = @{ 'Newsreader' = 'newsreader'; 'Inter' = 'inter'; 'IBM Plex Mono' = 'ibm-plex-mono' }
$rx    = [regex]"/\*\s*(?<sub>[\w-]+)\s*\*/\s*@font-face\s*\{(?<body>[^}]*)\}"
$faces = @()
foreach ($m in $rx.Matches($css)) {
  if ($m.Groups['sub'].Value -ne 'latin') { continue }   # latin subset covers our English text + punctuation
  $b   = $m.Groups['body'].Value
  $fam = ([regex]"font-family:\s*'([^']+)'").Match($b).Groups[1].Value
  $sty = ([regex]"font-style:\s*(\w+)").Match($b).Groups[1].Value
  $wgt = ([regex]"font-weight:\s*(\d+)").Match($b).Groups[1].Value
  $url = ([regex]"src:\s*url\(([^)]+)\)").Match($b).Groups[1].Value
  $ur  = ([regex]"unicode-range:\s*([^;]+);").Match($b).Groups[1].Value
  $name = $slug[$fam]
  if ($sty -eq 'italic') { $name += '-italic' }
  $name += "-$wgt.woff2"
  Invoke-WebRequest -Uri $url -UserAgent $ua -UseBasicParsing -OutFile (Join-Path $out $name)
  $faces += [pscustomobject]@{ fam = $fam; sty = $sty; wgt = $wgt; file = $name; ur = $ur }
  Write-Host "  downloaded $name"
}

if ($faces.Count -eq 0) { Write-Host "No latin faces parsed - leaving fallbacks in place."; return }

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("/* Self-hosted fonts. Generated by scripts/fetch-fonts.ps1 - do not hand-edit. */")
foreach ($f in $faces) {
  [void]$sb.AppendLine("@font-face {")
  [void]$sb.AppendLine("  font-family: '$($f.fam)';")
  [void]$sb.AppendLine("  font-style: $($f.sty);")
  [void]$sb.AppendLine("  font-weight: $($f.wgt);")
  [void]$sb.AppendLine("  font-display: swap;")
  [void]$sb.AppendLine("  src: url('./$($f.file)') format('woff2');")
  if ($f.ur) { [void]$sb.AppendLine("  unicode-range: $($f.ur);") }
  [void]$sb.AppendLine("}")
}
[System.IO.File]::WriteAllText((Join-Path $out 'fonts.css'), $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Wrote assets/fonts/fonts.css with $($faces.Count) faces."
